### ISSUE TITLE
Unpaired reads

### ISSUE THREAD

**Issue by alantsangmb** [rrwick/Unicycler#10]
I understand that paired end reads are required for unicycler.

Is there any way to relax this constraint and let unicycler accept unpaired end data as well?
(suppose I have unpaired reads from illumina and long reads from nanopore)

Thanks.

**Comment by rrwick** [comment]
This is definitely on my to-do list! There's no real reason why unpaired reads would be a problem, but I would need to fiddle with Unicycler's calls to SPAdes and Pilon. Ideally, Unicycler would happily take a combination of paired and unpaired reads, ideal for instances where you've used [FLASh](http://ccb.jhu.edu/software/FLASH/) or [PEAR](http://sco.h-its.org/exelixis/web/software/pear/) to combine overlapping pairs.

Interestingly, somebody else wanted the same feature, because I spotted [this fork](https://github.com/txje/Unicycler) of Unicycler. I've never actually tried this and I'm not sure if it's working or not - I've just briefly looked at [the code changes](https://github.com/rrwick/Unicycler/compare/master...txje:master). But when I get around to it, I may see if I can merge those changes into the main Unicycler repo.

**Comment by rrwick** [comment]
I've just implemented this in Unicycler's [development branch](https://github.com/rrwick/Unicycler/tree/development), so I'm going to close this issue now.

Keep in mind that the development branch may be broken at any time, so only install from it if you're feeling brave! The changes there should eventually make their way to the master branch, when I'm convinced they are reasonably stable.
