### ISSUE TITLE
Does two round of "no Pilon changes" before stopping?

### ISSUE THREAD

**Issue by tseemann** [rrwick/Unicycler#105]
Why is iteration 4 done?

```
Pilon polish round 1
Total number of changes: 17

Pilon polish round 2
Total number of changes: 5

Pilon polish round 3
No Pilon changes

Pilon polish round 4
No Pilon changes
```

**Comment by rrwick** [comment]
Sorry, Unicycler isn't making it clear exactly what it's doing. It first runs Pilon using `--fix bases`, where it only makes small scale changes. Only after this stops changing things does it switch to `--fix all`, where it tries local reassembly to improve regions. So for your assembly, it used `--fix bases` for the first three rounds, and then since it got no changes on the third, it tried `--fix all` for the fourth round (still getting no changes).

This logic is all somewhat ad hoc. Unicycler's polishing step needs a good overhaul one of these days!

**Comment by tseemann** [comment]
Ah ok that makes more sense.  Thanks!   Yes pilon needs replacing for all of us.
