### ISSUE TITLE
errors during spades Assembling no outputs

### ISSUE THREAD

**Issue by giampe79** [rrwick/Unicycler#12]
Dear Unicycler author,
I have tried Unicycler tool to assemble my genome (2,5 milion base) with a set of paired Illumina reads and a set of PacBio reads, I have used the docker container to run it. 
The run of command  failed , I;m reporting below the relative message, Could you help me to fix these errors?
COMMAND LAUNCHED:
c1780c8c[unicycler_input_result]# unicycler -1 RAMS001_dd_S28_L004_R1_001.fastq -2 RAMS001_dd_S28_L004_R2_001.fastq -l R125-G01.1-Reads.fastq -o ./output_dirUnicycler --pilon_path=/usr/local/share/pilon-1.20-0/pilon-1.20.jar

REPORT
Starting Unicycler
Command: /usr/local/bin/unicycler -1 RAMS001_dd_S28_L004_R1_001.fastq -2 RAMS001_dd_S28_L004_R2_001.fastq -l R125-G01.1-Reads.fastq -o ./output_dirUnicycler --pilon_path=/usr/local/share/pilon-1.20-0/pilon-1.20.jar

Making output directory:
  /home/unicycler_input_result/output_dirUnicycler

SPAdes read error correction
Command: /usr/local/bin/spades.py -1 /home/unicycler_input_result/RAMS001_dd_S28_L004_R1_001.fastq -2 /home/unicycler_input_result/RAMS001_dd_S28_L004_R2_001.fastq -o /home/unicycler_input_result/output_dirUnicycler/spades_assembly_temp/read_correction --threads 8 --only-error-correction

Corrected reads:
  /home/unicycler_input_result/output_dirUnicycler/spades_assembly_temp/corrected_1.fastq.gz
  /home/unicycler_input_result/output_dirUnicycler/spades_assembly_temp/corrected_2.fastq.gz
  /home/unicycler_input_result/output_dirUnicycler/spades_assembly_temp/corrected_u.fastq.gz

Choosing k-mer range for assembly
Median read length: 151
K-mer range: 27, 47, 63, 77, 89, 99, 107, 115, 121, 127

Conducting SPAdes assemblies
K-mer   Segments   Dead ends   Score
   27                          too complex
   47                          too complex
   63        325           0      3.08e-03
   77        260           0      3.85e-03
   89        178           0      5.62e-03
   99        157           0      6.37e-03
  107        139           0      7.19e-03
  115        124           0      8.06e-03
  121        115           0      8.70e-03
Traceback (most recent call last):
  File "/usr/local/bin/unicycler", line 11, in <module>
    load_entry_point('unicycler==0.2.0', 'console_scripts', 'unicycler')()
  File "/usr/local/lib/python3.5/site-packages/unicycler/unicycler.py", line 79, in main
    args.expected_linear_seqs)
  File "/usr/local/lib/python3.5/site-packages/unicycler/spades_func.py", line 152, in get_best_spades_graph
    row_extra_text={best_kmer_row: ' \u2190 best'})
  File "/usr/local/lib/python3.5/site-packages/unicycler/misc.py", line 628, in print_table
    print(indenter + row_str, flush=True)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2190' in position 48: ordinal not in range(128)
c1780c8c[unicycler_input_result]#

thanks in advance
Annalisa

**Comment by rrwick** [comment]
Hi Annalisa,

I'm happy to report that this bug has been fixed! https://github.com/rrwick/Unicycler/commit/c97159770522fb42fc749998350a81698870f273

The first (and simplest) solution would be to just run a more recent version of Unicycler through Docker:
```
docker run quay.io/biocontainers/unicycler:0.3.0b--py35_0 unicycler
```
I've updated the Unicycler README to show this one instead of the previous version (0.2.0) which still has the bug. However, this version isn't completely up-to-date. I've submitted an updated recipe to BioConda for the new version I just made (v0.3.0), but I must confess that I'm not very savvy with this Bioconda/BioContainers stuff.

Alternatively, you could [clone and install Unicycler yourself](https://github.com/rrwick/Unicycler#install-from-source), without Docker. This will let you get the most recent version, but you'll have to make sure you have all the other dependencies installed, like SPAdes.

Ryan
