### ISSUE TITLE
Edge support

### ISSUE THREAD

**Issue by sjackman** [rrwick/Unicycler#120]
I've assembled a genome that's in five pieces. I'd like to know the number of long reads (and short reads, but particularly long reads) that span each GFA edge. Could Unicycler output this information in the link `L` records? The GFA spec has the read count `RC` optional attribute for this purpose. https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md#optional-fields-3

In the mean time, I'll try aligning the long reads to the graph using `unicycler_align` and `spades-gmapper`.
https://github.com/rrwick/Unicycler/blob/master/docs/unicycler-align.md
http://cab.spbu.ru/files/release3.12.0/manual.html#sec4.3

**Comment by rrwick** [comment]
That would be possible, but it'd take a bit of fiddling around because Unicycler has a few different ways of scaffolding the graph, some of which could be assigned long read counts and others that couldn't.

I haven't yet tried `spades-gmapper`, so that might be a good option. One thing to note, though - SPAdes graphs have overlap across the edges and Unicycler graphs don't. I'm not sure if that matters or not. I see it has a `-k` option which might (though this is just speculation) be used to indicate the overlap. Just be cautious!

When I have odd assemblies like this, my usually mode of investigation is to [isolate the reads in the vicinity of the problem](https://github.com/rrwick/Unicycler/wiki/Read-extraction) and then BLAST the reads to the graph in Bandage ([example case](https://github.com/rrwick/Unicycler/wiki/Tangled-small-plasmids)). I can then sometimes wrap my head around what's going on.

Ryan

**Comment by sjackman** [comment]
Thanks for the tip on BLASTing the long reads, Rayan. I'll try that out!

**Comment by sjackman** [comment]
`spades-gmapper` does expect each edge to be a *k*-1 bp overlap. The assembly graph would need to be deblunted for `spades-gmapper`.
See  https://github.com/ablab/spades/issues/160#issuecomment-414600932

**Comment by sjackman** [comment]
`Bandage querypaths` however accomplished exactly what I wanted! It mapped the long reads to the blunt assembly graph (Unicycler or Flye), and output paths! I'm trying to accomplish the same task now using `unicycler_align`, to compare results.

See https://github.com/rrwick/Bandage/wiki/BLAST-searches#query-paths
and https://github.com/rrwick/Bandage/wiki/Command-line#bandage-querypaths
and https://github.com/rrwick/Bandage/wiki/Graph-paths
and https://github.com/rrwick/Unicycler/blob/master/docs/unicycler-align.md

**Comment by rrwick** [comment]
Thanks for the update - glad `Bandage querypaths` worked. As I recently commented in #130, I fear `unicycler_align` isn't going to be the right tool for the job.

Ryan
