### ISSUE TITLE
Unicycler works on pore-chopped reads only??

### ISSUE THREAD

**Issue by kinza-asif** [rrwick/Unicycler#131]
Hi rrwick, 

I am using Unicycler for ONT(long reads) assembly only. Unicycler is not running on the raw reads rather it runs on pore-chopped read. Does it only run on reads that have been pore-chopped?
Now I am using reads that have been chopped off adapters and barcodes but, for one of my assembly it says "miniasm assembly failed; empty results".
What could be the possible reasons for this?

Thanks
Regards

Kinza

**Comment by rrwick** [comment]
Unicycler may not require adapter-trimmed reads, but it is a good idea. Especially with a barcoded run, the pre-trimmed reads may have quite a lot of adapter sequence on them.

As for why the miniasm assembly failed... that isn't necessarily a problem. Did that assembly have very few Nanopore reads? The miniasm step only works well with reasonably high Nanopore read depth. But that's okay, because Unicycler separately tries to make bridges by aligning the Nanopore reads to the graph, which works well with low Nanopore depth.

Ryan
