### ISSUE TITLE
optimal k-mer selection fail

### ISSUE THREAD

**Issue by berkell** [rrwick/Unicycler#218]
Hi,

I'm trying to run a fresh conda installation with unicycler, but have issues with the spades assembly as all but the 127 k-mer assembly is listed as failed. I had this issue previously as well, and then feeding the assembler the spades path worked, but since installing it again this doesn't solve the issue. I've tested spades separately and it works as it should so this can't be the issue. 

I run the following command

unicycler -1 R1.fastq.gz -2 R2.fastq.gz -l assembly.fasta -o uni_out -t 16 --keep 0 --spades_path /home/user/tools/SPAdes-3.13.1-Linux/bin/spades.py --mode bold

And my problem is this:
SPAdes assemblies (2019-12-03 14:36:52)
---------------------------------------
    Unicycler now uses SPAdes to assemble the short reads. It scores the assembly graph for each k-mer using the number of contigs (fewer is better) and the number of dead ends (fewer is better). The score function is 1/(c*(d+2)), where c is the contig count and d is the dead end count.

K-mer   Contigs   Dead ends   Score   
   27                           failed
   47                           failed
   63                           failed
   77                           failed
   89                           failed
   99                           failed
  107                           failed
  115                           failed
  121                           failed
  127       203         203   2.40e-05 <-best

Any ideas as what might solve this issue? 

Thanks in advance!

**Comment by fengyuchengdu** [comment]
Yeah I've got the same problem. It used to be working if I downgraded SPAdes to 3.13.1 from 3.13.2, however this solution dies for now.

**Comment by fengyuchengdu** [comment]
Rolling back to SPAdes 3.13.0 solves problem.

**Comment by ilnamkang** [comment]
I've got the same problem for SPAdes 3.14.0.

**Comment by Koen-vdl** [comment]
I was experiencing the same issue with both Spades 3.14.0 and 3.13.1. By rolling back to 3.13.0 (as suggested by @fengyuchengdu) the kmer selection step finished successfully.

**Comment by wanyuac** [comment]
> Rolling back to SPAdes 3.13.0 solves problem.

Yes, @fengyuchengdu is correct. The k-mer optimisation works under SPAdes 3.13.0 but does not work under any later versions due to the reason I explained in Issue #225 . Therefore, Unicycler is compatible to SPAdes 3.6.2 – 3.13.0.

I believe that this is a critical issue for the quality of short-read assembly and the accuracy of hybrid assembly because without the k-mer optimisation, for every genome Unicycler can only use the k-mer graph of the greatest `k` for downstream steps. Nonetheless, this k-mer graph often have a higher number of dead ends (including singleton contigs) than k-mer graphs of a smaller `k`, leading to an incomplete genome assembly (namely, with uncircularised contigs) or even erroneous contig circularisation — I have an example where a plasmid genome became a smaller circular plasmid and a singleton contig in the assembly graph. Therefore, for the long-term use of Unicycler, it is desirable to fix this issue rather than noting compatible SPAdes versions (and they are old versions) in Unicycler's manual.

**Comment by loganvoegtly** [comment]
From what I can tell this occurred with the SPAdes developers pushed a commit to "reduce contig output"

[https://github.com/ablab/spades/commit/bd7c13538c914d7b9c1dba80dc72240554b708ee](url)

They also insist, regarding using anything but the final graph is "Well, this is a bit wrong approach as I already said – the intermediate iterations of SPAdes are quite different from the last one."

[https://github.com/ablab/spades/issues/353](url)

**Comment by wanyuac** [comment]
From Issue 353,

> The intermediate steps of SPAdes are quite special and the results are intended for internal consumption only.

So this commit actually makes the optimisation of k-mers much harder and slower than before.

**Comment by rrwick** [comment]
I'm working on a new version of Unicycler (v0.5.0) which has been designed to work with modern versions of SPAdes, which should fix this issue! Unfortunately, as @wanyuac realised, this comes with a performance hit, as Unicycler now needs to run SPAdes with the `--restart-from` option, leading to some redundancy, but I decided that the tradeoff was worth it.
