### ISSUE TITLE
Single end assembly in unicycler?

### ISSUE THREAD

**Issue by appliedmicrobiologyresearch** [rrwick/Unicycler#274]
I've been using your assemblers for years, but I now have an issue. I'm trying to assemble some old data where R2 is such bad quality, for some reason, that all the R2s get rejected by trimmomatic. So I was trying to run unicycler with the unpaired R1s, but it still requires -1 and -2 options. Is there a way round this so it is happy just with -s? This would also be useful for our miniseq data. Cheers!

**Comment by roltim00** [comment]
Running into the same type of problem.

**Comment by marcomeola** [comment]
Any updates on this one? Have same issue

**Comment by StefDiV** [comment]
Reporting same issue here. 
Looking forward for an update on this.

**Comment by rrwick** [comment]
I'm working on a new version of Unicycler now (v0.5.0) and I can't replicate this problem. Unpaired assemblies are working for both short-read-only:
```
unicycler -s illumina_1.fastq.gz -o assembly
```
And hybrid datasets:
```
unicycler -s illumina_1.fastq.gz -l nanopore.fastq.gz -o assembly
```

I don't understand what the problem was - I thought this should have always worked. But it at least seems to be working in  the new version 🤷  So I'm going to close this issue now, but if the problem persists in v0.5.0, please let me know in a new issue. Thanks!
