### ISSUE TITLE
Segfault error during hybrid assembly - aligning long read step 

### ISSUE THREAD

**Issue by naturepoker** [rrwick/Unicycler#281]
I'm running a de novo assembly of a microbial genome with expected size of about 4mb. 
The process take a couple of days, but the assembly cancels out with a segfault error at a little above 70% completion of aligning long reads to graph step, with below error message 

`Dec 14 07:52:30 mainmachine kernel: [9650339.362961] python[10608]: segfault at 7fea28000000 ip 00007ff87cb2030e sp 00007ff6f71d2c80 error 4 in cpp_functions.so[7ff87cb06000+cb000]
Dec 14 07:52:30 mainmachine kernel: [9650339.362973] Code: 01 d6 48 39 9d 70 fb ff ff 0f 84 35 03 00 00 48 8b 85 10 fc ff ff 89 da 0f b6 34 18 48 8b 85 30 fc ff ff 40 88 b5 90 fb ff ff <44> 0f b6 24 18 40 80 fe 2d 0f 84 e3 00 00 00 41 80 fc 2d 0f 84 09`

I'm running the process on a local machine with 128GB of ram, 32 threads. 
Short reads data size is about 1.2GB each, and the long read data file is about 17GB. 

Could this be due to low memory? Unicycler seemed to be stable at a far lower ram usage for most of the process, so I'm not sure if we're looking at a simply memory error. 

I'd appreciate any advice, thank you!

**Comment by rrwick** [comment]
It's tough to say for certain, but I'd guess the problem is one of the following:
* There is a particular long read in your set that (for some reason) is causing the crash.
* The large number of long reads is making you run out of memory (as you suspected).

17 GB is a _lot_ of long reads, far more than Unicycler needs, so I'd suggest subsampling that way down (e.g. to 1 GB) and trying again. That will hopefully solve the problem for either possible cause.

Since you have so many long reads, I'd also recommend trying a long-read-first approach to hybrid assembly. See the brief note [here](https://github.com/rrwick/Unicycler#a-note-on-trycycler) and the more extensive guide [here](https://github.com/rrwick/Trycycler/wiki/Guide-to-bacterial-genome-assembly).

Ryan
