### ISSUE TITLE
Java dependency check uses incorrect regex

### ISSUE THREAD

**Issue by aruginkgo** [rrwick/Unicycler#283]
I believe this is related to [this issue](https://github.com/rrwick/Unicycler/issues/216) as well and results from the logic around this area: https://github.com/rrwick/Unicycler/blob/ba23ffc40464391aa52ba8afc54ebf4073ef184b/unicycler/misc.py#L1088

`apt-get install default-jre` on Ubuntu 20.04 results in `java -version` returning 

```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 17+35-Ubuntu-120.04, mixed mode, sharing)
```

I think it might be failing because it doesn't have a period in it.

I was about to test this hypothesis but I see that @rrwick's latest version removes Pilon 😭

**Comment by rrwick** [comment]
That's right - I'm working on a new version at the moment, and I'm dropping Pilon polishing because:
* The many-rounds approach to polishing was slow.
* I don't think polishing is usually needed for short-read-only assemblies.
* There are better polishers for hybrid assemblies. I'm fond of Polypolish (my own), POLCA, NextPolish and HyPo.

For these reasons, I had gotten in the habit of running Unicycler with `--no_pilon`, so I decided to make that official in the new version.

Ryan

**Comment by aruginkgo** [comment]
Thank you for the quick response and alternative hybrid polishers! I'll look into those.

**Comment by rrwick** [comment]
Check out the Polypolish paper for a much deeper dive into polishing completed bacterial genomes:
https://www.biorxiv.org/lookup/doi/10.1101/2021.10.14.464465
