### ISSUE TITLE
Update Unicycler

### ISSUE THREAD

**Issue by termithorbor** [rrwick/Unicycler#288]
Hi,

how can I update to the new version of Unicycler when I just followed the installation instructions here to install 0.4.9b0?
Thanks in advance :)

**Comment by rrwick** [comment]
The [installation instructions on Unicycler's README](https://github.com/rrwick/Unicycler#installation) use Unicycler's main branch, so that should be the most up-to-date. This will include any changes that I've pushed to GitHub but not yet put in a new release.

If you'd specifically like an exact release (like v0.5.0), you can download the source code from the [release page](https://github.com/rrwick/Unicycler/releases) instead of running `git clone`.

Ryan
