### ISSUE TITLE
Some doubts about Unicycler

### ISSUE THREAD

**Issue by RyanBio** [rrwick/Unicycler#32]
Hi,
Unicycler is really a great pipeline with many useful tools. Although, I still have some doubts about its application and some steps, like the graph scaffolding and bridging:
1. Does Unicycler only use for bacterial genomes? How about a small diploid genome?
2. Long read bridging says it makes long-read bridges directly by semi-globally aligning the long reads to the **assembly graph**. In Unicycler pipeline, I find the assembly graph can be generated by spades. Is there any other way to get an assembly graph?

Thanks,
Ryan

**Comment by rrwick** [comment]
Hi Ryan (I'm Ryan too - this could be confusing),

Yes, Unicycler is designed exclusively for bacterial genomes. You can of course try it on a small diploid genome, but I make no promises! If it works, great, but I probably won't debug odd behaviour on diploid eukaryotes. Sorry!

Regarding the assembly graph, yes, Unicycler always builds it with SPAdes. I've tried quite a few assemblers and am generally happy with SPAdes' Illumina read assembly graphs. Since each assembler has its nuances in assembly graph implementation, it wouldn't be easy to swap out SPAdes for another assembler. You're welcome to fork Unicycler and try new things, but I fear that replacing the short read assembler might require a lot of work.

Ryan
