### ISSUE TITLE
Error: SPAdes encountered an error

### ISSUE THREAD

**Issue by louisvant** [rrwick/Unicycler#332]
Hi, dear, 
I always meet this error when run the hybrid assembly : Error: SPAdes encountered an error. While i used the hybrid assembly used the test data, there is no error. 
The data of short reads i used was approximate 10GB each, and the long reads was about 14GB.

Here is the unicycler log and spades log.
Any one can figure out why this happened and how to solve it?

[spades.log](https://github.com/rrwick/Unicycler/files/14207736/spades.log)
[unicycler.log](https://github.com/rrwick/Unicycler/files/14207737/unicycler.log)

**Comment by rrwick** [comment]
This is the SPAdes error in your log:
> == Error ==  system call for: "['/home/FengC_Biolab/software/miniconda3/envs/mito/bin/spades-core', '/home/FengC_Biolab/temp/mito/pc/unicy/spades_assembly/K27/configs/config.info', '/home/FengC_Biolab/temp/mito/pc/unicy/spades_assembly/K27/configs/isolate_mode.info']" finished abnormally, OS return value: -9

That's not very informative, so I don't know what the problem is. You could try running SPAdes on its own (not via Unicycler) to see if that works.

20GB of short reads is a lot! I saw `mito` in your paths - is this a mitochondrial genome? If so, your read coverage is excessively high, and subsampling your reads might help.

And if this is a larger eukaryote genome, then Unicycler is probably not the right tool for the job - it was designed specifically for bacterial genomes.

**Comment by louisvant** [comment]
Thank you very much.

i used to run the spades.py independently and it ran ok. 
The data was used to assembly for a plant mitogenome. I have try to subsample the data into a total 5GB of short reads, and it is still not work. 
so i dont know how to solve this problem.

**Comment by rrwick** [comment]
That may still be excessively deep, depending on the size of the mitochondrial genome. I'd aim for ~100-200x depth, and see if that works. If not, then I'm not sure!

Also, I don't have much experience with plant mitochondrial genomes. If they are very different from bacterial genomes (e.g. much more repetitive), then Unicycler's assumptions may be violated and it may not be the right tool.

**Comment by louisvant** [comment]
thank you for your replies and suggestions, 
best wishes.
