### ISSUE TITLE
Running Illumina-only assembly with options -1, -2, and -s altogether

### ISSUE THREAD

**Issue by santiagorevale** [rrwick/Unicycler#341]
Hi there!

I was wondering if you could help with the following scenario. I have an Illumina PE sample where I perform some adapter trimming and read merging. Because of the read merging, I could end up with 3 resulting files:

- shortreads.filtered.R1.fastq.gz
- shortreads.filtered.R2.fastq.gz
- shortreads.merged.fastq.gz

Would "Unicycler" work better if I provide all three inputs instead of just the filtered PE files? As in:

```bash
unicycler \
    -1 shortreads.filtered.R1.fastq.gz \
    -2 shortreads.filtered.R2.fastq.gz \
    -s shortreads.merged.fastq.gz \
    --out .
```

Or would it be better not to mix PE with SE reads? These won't be long reads, because they would be the result of merging 250 bp PE reads, which could be around 475 bp, give or take?

Thank you very much in advance for your thoughts.

**Comment by rrwick** [comment]
I'm not sure, but you could different combinations and see how they perform. Some metrics to consider:
* [dead-end count](https://github.com/rrwick/GFA-dead-end-counter) (lower is better)
* contig count (lower is better)
* contig N50 (higher is better)

My prediction is that the different approaches will perform similarly, so it won't actually matter too much. Personally, I no longer bother merging paired-end reads because I rarely found it made a significant improvement.

Ryan
