### ISSUE TITLE
Sample links seem to be out

### ISSUE THREAD

**Issue by ggautreau** [rrwick/Unicycler#35]
Hi Ryan,

The links on this page : https://github.com/rrwick/Unicycler/tree/master/sample_data for the Helicobacter pylori, Streptococcus pyogenes and Neisseria gonorrhoeae organisms seem to be out of service.

Please, can you restore them ? 

Thx.

**Comment by rrwick** [comment]
Sorry for the delayed response, but I just tried the links and they are working for me now. How about you? Maybe it was a figshare issue when you were trying to download them?

Ryan

**Comment by msejourne** [comment]
Ryan, 
I am on the same laboratory as Guillaume and we tried to download files from figshare website. After several tries, among all the proposed links, we found one that allowed us to download sample data.

Marine

**Comment by rrwick** [comment]
That's odd, but I'm going to put the blame on figshare! 

In case it helps to download the files from the figshare page (instead of via a direct link), I've updated the [sample data README](https://github.com/rrwick/Unicycler/tree/master/sample_data) to have links directly to these pages:
* https://figshare.com/articles/Synthetic_Shigella_plasmid_reads/5165776
* https://figshare.com/articles/Helicobacter_pylori_SAMN06173313_reads/5165782
* https://figshare.com/articles/Streptococcus_pyogenes_SAMN04875527_reads/5165788
* https://figshare.com/articles/Neisseria_gonorrhoeae_SAMN04875541_reads/5165809

Thanks!
