### ISSUE TITLE
Public docker image

### ISSUE THREAD

**Issue by sminot** [rrwick/Unicycler#37]
It might be worth noting in the Readme that you can find a publicly accessible Docker image for Unicycler at quay.io/biocontainers/unicycler. That can be helpful when there's a program with so many dependencies. You can also include a note on running an assembly with the docker image in a single line, e.g.:

```
docker run --rm -v $PWD:/share quay.io/biocontainers/unicycler:0.3.0b--py35_1 /bin/bash -c "cd /share; unicycler -1 read1.fastq.gz -2 read2.fastq.gz -l long_reads.fastq.gz -o output_dir"
```

**Comment by rrwick** [comment]
I did have that in the README, but actually took it out because the Unicycler version in the Docker image is a bit old. I was getting a handful of bug reports for already-fixed bugs! So I'm concerned that advertising the Docker image will discourage people from using a current version.

Someday, when development on Unicycler has settled down, I'll revisit making a Biocontainers Docker image and add it back in. Thanks!
