### ISSUE TITLE
retain bubbles in assembly graph

### ISSUE THREAD

**Issue by shilpagarg** [rrwick/Unicycler#41]
Hi, I am using unicycler assembler for yeast pseudo-diploid genome using short illumina reads? I would like to retain bubbles in the graph, I am using ```no_correct``` option, but I dont see the bubbles in graph? 
How can I retain bubbles in the graph? 

Attached snapshot
![unicycler_graph](https://user-images.githubusercontent.com/7416551/28755373-cf817d60-7559-11e7-9052-4b2407af6f87.png)

**Comment by rrwick** [comment]
I'm not exactly sure. I should first say that Unicycler is explicitly designed for haploid bacterial genomes, so I've never tested it much on yeast or any eukaryote. It may fail on diploid genomes - especially when it tries to decide whether a contig is single-copy or multi-copy. Also, I'm not sure what 'pseudodiploid' means for a yeast genome... could you elaborate?

Unicycler doesn't explicitly pop bubbles, so if there should be bubbles in the graph that you aren't seeing, maybe the bubble popping is occurring in SPAdes? Again, I fear there's no good answer because Unicycler really is intended for haploid genomes.

And as a final note, that Illumina graph looks pretty rough - lots of separate fragments and dead ends. Unicycler definitely performs better on Illumina read sets with better coverage (i.e. fewer dead ends), so perhaps that's causing problems as well.

Ryan

**Comment by rrwick** [comment]
This issue is pretty old, so I'm going to close it now, but please let me know if you still have questions.

Ryan
