### ISSUE TITLE
Question: How many iterations of Racon polishing should I expect???

### ISSUE THREAD

**Issue by judzen** [rrwick/Unicycler#51]
Hello:  Right now, I am performing a hybrid assembly of Illumina MiSEQ & ONT minION R9 reads.  

Thanks to the great documentation for Unicycler, everything has been straightforward getting all of the prerequisites built, etc. & submitting the primary command for the pipeline.  

I have noticed, however, that it has been polishing w/Racon for some time now (~18 days over a total of 10 iterations).  

The command that I submitted was the following:  
unicycler -t 22 -1 R1_001.fastq -2 R2_001.fastq -l ONT_Reads_DeDuped.fq -o HYBRID --verbosity 2 --vcf --linear_seqs 3

While hardware platforms & OSes differ, I was just wondering how many iterations of polishing with Racon I could potentially expect as the pipeline completes.  If I recall correctly, Racon is version 0.5.0 from when I built the pipeline.  

Thank you kindly for your amazing documentation & remarkable application!
-J

**Comment by rrwick** [comment]
18 days is a long time - we'll have to do better than that! Unicycler polishes with Racon until it stops seeing an improvement, which sometimes takes about 10 iterations or more. In my experience this can take a few hours, but never days.

I have come to realise that the vast majority of the improvement is in the first few rounds of Racon, so I recently set a maximum of five Racon rounds (https://github.com/rrwick/Unicycler/commit/65313238c5e3e822da0d01461e24e9e3b600328b). This change is currently in Unicycler's [development branch](https://github.com/rrwick/Unicycler/tree/development), but it should eventually make its way to the master branch when I do the next release. So that's one option: grab the development branch of Unicycler. However, if you're taking 18 days to do 10 rounds of polishing, the new limit (5 rounds) will take about 9 days which is still way too long!

Is this a bacterial genome you're assembling? I see `--linear_seqs 3` in your command which makes me worried that you might be trying to assemble a eukaryote 😬  You're of course welcome to try, but Unicycler is designed for and tested on bacterial genomes only, so you'll be straying into uncharted territory. I suspect that small haploid eukaryote genomes (like yeast) will be okay, but Unicycler may perform poorly on larger diploid genomes.

How big is your set of ONT reads? If it's huge (many Gbp), that might be the problem. I wrote [Filtlong](https://github.com/rrwick/Filtlong) for this scenario: when you have tons of long reads it can subsample for just the best ones. I think anything over 100x depth is probably overkill, so a 5 Mbp genome probably doesn't need more than 500 Mbp of long reads (especially if they are a high-quality subsample).

Let me know how you go!
Ryan

**Comment by judzen** [comment]
Thanks for your thoughtful reply, Ryan-- I have provided answers to your questions below, but would first like to include some info on our setup/configuration.  

Though we're running 22 threads, our hardware has ~20GB RAM, so that is an additional consideration when considering our run time/walltime.  

Also, since asking about the number of iterative polishing steps, it has stopped (at either 12 or 15) and moved on to read alignment, which is great!  :)  

In the command, I selected -- linear_seqs 3, as I am expecting our species to have 2 chromosomes & 1 plasmid.  Among all of the replicons, I would estimate a total size of 5.2 Mbp for this assembly.  If I've misinterpreted the "linear_seqs" command, please let me know & we will certainly change it for future hybrid assemblies.  

For the ONT reads, we have a total of 17,800 reads (after de-duplication with dedupe.sh in BBMap).  I would really have to dig through things to determine the size distribution of the input data-- sorry.  I've run the minimap > miniasm > Racon workflow outside of Unicycler (albiet on a different platform) and Racon yields a consensus assembly for the ONT data independently.  (This is solely for internal comparison(s) & our general curiosity.)  

For what it's worth, I've used dedupe.sh at the suggestion of the minimap author, who fielded many questions of mine patiently suggesting that I have duplicate reads.  Though dedupe.sh was not suggested for this purpose, it was something that I knew would work (based on previous experience).  

Should Filtlong perform de-duplication as well as the subsampling that you've mentioned, that would be a great addition to our pre-processing steps.   

Thanks again for your continued assistance!!!

**Comment by rrwick** [comment]
Regarding the `--linear_seq` option - I would only set that if you know your genome has linear chromosomes/plasmids. Most bacterial chromosomes/plasmids are circular, and if that's the case for your bug, you should leave this option out. That being said, it probably isn't affecting your results much.

17,800 reads doesn't sound like a huge number. If you have a nice mean length of 10 kbp, that would only result in 178 Mbp of reads in total, about 34x depth. So, your genome isn't huge and your read set isn't huge... I'm still not sure why Racon is taking so long.

It could be that you've chosen _too many_ threads. 22 threads and 20 GB of RAM gives less than 1 GB of RAM per thread, so that could be the problem. Maybe your computer is using the swap space and that's slowing it down? Maybe something like 6 threads would work better.

Another possibility: maybe dedupe.sh is producing an odd subset of reads that is confusing Racon somehow. That's vague speculation, I know. Perhaps you could try Filtlong instead of dedupe.sh and see if it makes any difference. Filtlong doesn't specifically try to _de-duplicate_ the reads, it subsamples based on quality (which would result in some amount of de-duplication).

Ryan

**Comment by judzen** [comment]
Just a quick update:  I have performed the following steps since your follow up message...
a.  installed the dev version, 0.4.2 to reduce the number of Racon polishing steps to 5
b.  installed new RAM; decreased thread count to 10 so that each thread has 12.8 GB of memory avail
c.  used a filtlong subset of reads as Unicycler input (default command reduced input file size from ~7 GB to 1 GB)

Have you noted any issues recently with Racon?  In a recent assembly it seemed to lock-up at the first iteration of polishing.  I'm re-running this assembly to see if it continues to do so...  I wasn't able to get a version number straightforwardly from it-- if that is still problematic, I will update it should this iteration not completed.  

Thanks again,
J

**Comment by rrwick** [comment]
No, I haven't noticed Racon issues myself. It sounds to me like you're doing everything right, so I hope it works!

If it still locks up, and assuming there aren't data privacy issues, perhaps you could share the reads with me and I can try myself? I could make a Dropbox directory for you to upload to. If it worked fine for me, then we could narrow down the problem to your configuration. If I see the same problem, then the read set and/or Racon might be the issue.

Let me know how you go!

Ryan

**Comment by tseemann** [comment]
@judzen have you just tried a `canu` assembly of your ONT data? to see it even makes sense?

**Comment by judzen** [comment]
@tseemann -- Canu is not an option for us b/c it does not pass grid (PBS Pro job manager) flags correctly.  

The good news is that-- after upgrading hardware and snagged the dev fork (for <5 iterations of Racon polishing)-- I was able to dedicate ~12 GB/thread across 10 threads & the assemblies of interest completed w/Unicycler.  

As an aside, the final iteration of Pilon tanked-- I am not sure why-- but I did use the flag to save all intermediate files (so that I can revisit the Pilon error later).  

Has anyone updated to the newest version(s) of XCode & Java (version 9)???  I'd like to know if there are any problems (aside from how Java 9 is now branded/labeled, e.g. 9.x vs 1.8.x) between these dependencies & Unicycler.  It appears that we have things working well now and I don't want to mess up the config with "upgrades" (or updates, etc.).  

Thanks to everyone for their continued assistance!

**Comment by rrwick** [comment]
That recent Java version change did in fact cause a problem with Unicycler, but it was fixed in v0.4.3. However, I ended up downgrading Java back to v1.8 because I couldn't make [FigTree](http://tree.bio.ed.ac.uk/software/figtree/) work with v9. Also, I'm using Xcode v9 and haven't hit any Unicycler issues.

I'm going to close this issue now, but let me know if you have any more concerns. And if Pilon continues to be problematic, perhaps open a new issue for that?

Thanks,
Ryan
