### ISSUE TITLE
Python unexpected shut down right after minimap overlap finding

### ISSUE THREAD

**Issue by Mbf001** [rrwick/Unicycler#53]
I have a problem running de long reads only mode of the software; right after find the overlaps with minimap  and find 'segmentation fault: 11'  It immediately shut down the program. Any tips?

**Comment by rrwick** [comment]
It sounds like it crashed in the C++ code, which makes me suspect the problem is with the compilation or the environment.

First of all, are you using the latest version? I've fixed a few bugs recently, so make sure you're using v0.4.1.

If you're seeing the crash on the current version, you might want to look at #42 and #43. Let me know how you go!

Ryan

**Comment by Mbf001** [comment]
Hi Ryan, thanks for the answer. 
I´m using current version. 
It seems to be  memory problem, I´m using a MinION dataset  that probably overload the memory. I´ll try to request more memory and see if that works.

Miguel

**Comment by rrwick** [comment]
Glad you figured it out!

For what it's worth, I've found that excessively deep long reads don't help Unicycler, so if you have a lot you should subsample for the better ones. 50x to 100x depth should be plenty, which is only about 500 Mbp of reads, even for a larger bacterial genome.

I wrote [Filtlong](https://github.com/rrwick/Filtlong) for exactly this purpose. Give it a try: it might help your RAM issues, shorten Unicycler's running time and possibly improve the assembly as well.

Ryan
