### ISSUE TITLE
Pilon Polishing fails when using Bowtie2 v. 2.3.3 but works correctly with v. 2.3.0

### ISSUE THREAD

**Issue by jrober84** [rrwick/Unicycler#62]
The error below is produced when running pilon with the brew version of Bowtie v. 2.3.3  but will work correctly if an earlier version v. 2.3.0 is installed from sourceforge. 

Unable to polish assembly using Pilon: Bowtie2 encountered an error:
Error parsing alignment policy setting 'SEED'; RHS must have 1 token, had 2.  Policy: 'SEED=0;SEEDLEN=20;DPS=15;ROUNDS=2;IVAL=S,1,0.75;SEED=0,22;DPS=10;ROUNDS=2;IVAL=S,1,1.75'
Error: Encountered internal Bowtie 2 exception (#1)
Command: /home/linuxbrew/.linuxbrew/bin/../Cellar/bowtie2/2.3.3/bin/bowtie2-align-s --wrapper basic-0 -x 0_insert_size_check.fasta --local --fast-local --threads 16 -I 0 -X 5000 -S 0_alignments.sam -1 /home/jrobertson/__Assembly/illumina/SA20053897/SA20053897_S19_L001_R1_001.fastq -2 /home/jrobertson/__Assembly/illumina/SA20053897/SA20053897_S19_L001_R2_001.fastq
(ERR): bowtie2-align exited with value 1

**Comment by rrwick** [comment]
This is an odd one - I suspect it's a Bowtie 2 bug with the `--fast-local` option, but I don't fully understand it. I think it's already fixed in the current Unicycler version (v0.4.2) where I [changed the Bowtie2 call](https://github.com/rrwick/Unicycler/commit/51da5cdd891a30e910749d13ba59a9972333f8bd) to use `--fast` instead.

I'm going to close this issue now, but if you still see a problem in Unicycler v0.4.2, please let me know and I'll reopen it!

Ryan

**Comment by tseemann** [comment]
We also had this bug. Thanks for fixing.
