### ISSUE TITLE
Genome coverage

### ISSUE THREAD

**Issue by natachacouto** [rrwick/Unicycler#67]
Hey Ryan, how can I get information on the genome coverage when doing a hybrid assembly?

**Comment by rrwick** [comment]
'Genome coverage' can be a somewhat ambiguous term, especially when dealing with hybrid assemblies. I assume you mean the average read depth? Since a hybrid assembly has two read sets, this could mean Illumina read depth, long read depth or the sum of the two.

Unicycler only reports Illumina read depth in its hybrid assemblies for two reasons:
1. It internally uses an Illumina-assembly-graph-first approach to hybrid assembly.
2. I think that Illumina depth is more accurate for small plasmids (see last supplementary figure in [this paper](http://mgen.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000132)).

Unicycler saves per-contig Illumina-depth in the GFA file (look for `dp:f:` at the end of segment lines) and in the FASTA file (look for `depth=` in header lines). It does not report long read depth, though. You can estimate the whole-assembly long read depth with (total long read bases) / (assembly size), but I don't know an easy way to get a per-contig value.

Ryan
