### ISSUE TITLE
Keeping an assembly.log file in outputdir

### ISSUE THREAD

**Issue by tseemann** [rrwick/Unicycler#7]
When I run Unicycler, I end up with two files `assembly.fasta` and `assembly,gfa`.

The nice progress log and bridge and circularization summaries are lost in my scrollback.

Is there a way to keep it?
(besides saving stdout/stderr with all the ANSI ESC codes)

**Comment by rrwick** [comment]
Yeah, this is definitely on my to-do list: a log file which saves the output, but without ANSI formatting and without progress updates (`97.4%`, `97.5%`, etc).

Since I haven't implemented it yet, I'll ask for your opinions on the details. How verbose should the log file be? Verbosity level 1 (the default for stdout) is fairly concise. Verbosity level 2 includes all of the SPAdes output and information about each and every long read alignment. For example:
```
10046/81039: m151007_093400_42267_c100833102550000001823176711251513_s1_p0/22225/0_6313 (6313 bp)
  Ref name  Ref start  Ref end  Read start  Read end  Strand  Raw score  Scaled score  Identity
        71       3542     6933           0      3165       +       6582         87.49    85.14%
       112          0     1954        3090      4926       +       3823         87.60    85.46%
        90          0     1577        4834      6313       +       3104         87.77    85.62%
```
If you have a large set of long reads, verbosity level 2 could result in a 30+ Mb log file. Is that useful or just annoying?

I could make an option `--log_verbosity` which would mimic the `--verbosity` option for stdout. The default could be `1` but users could crank it up if they wanted more... Thoughts?

**Comment by rrwick** [comment]
I've finally implemented this and pushed the changes up to Unicycler's [development branch](https://github.com/rrwick/Unicycler/tree/development).

Unicycler now produces a `unicycler.log` file in its output directory. It follows the same verbosity level as stdout (as dictated by `--verbosity`), with the exception that if you set `--verbosity 0`, Unicycler will produce no stdout but still make a verbosity=1 log file.

I may have a few more kinks to iron out (particularly with the other executable scripts `unicycler_align`, `unicycler_check` and `unicycler_polish`) but the main `unicycler` program seems good now if you want to give the development version a go. Otherwise, this stuff should make its way to the master branch eventually!
