### ISSUE TITLE
unicycler_polish finished successfully, but there was a core dump at the start

### ISSUE THREAD

**Issue by sarahshah** [rrwick/Unicycler#79]
This is not an issue, but more of a curious observation. I used unicycler v0.3.1 to polish a long-read assembly with short reads. Everything ran smoothly and finished, but there was a "core" dump right after I launched the job on a cluster, and the job kept running. Just wondering why this happened. The log file didn't seem to report anything unusual.

**Comment by rrwick** [comment]
That is odd, though the `unicycler_polish` script is pretty clunky and due to be replaced, so I'm probably not going to debug this one.

For the relatively simple case of polishing a long read assembly using only short reads, I have recently made another script you might want to try:
https://github.com/rrwick/Unicycler/blob/development/scripts/pilon_polish.py

It's currently just in the development branch, but it will make its way to the master branch eventually. It essentially mimics what Unicycler does at the end of a hybrid assembly: multiple rounds of Pilon (up to 10 or until it stops making changes) rotating circular replicons between rounds. It does require a GFA input assembly, so it can tell what is and isn't circular. It's a stand-alone script, but it does require that Unicycler is installed so Python can import bits of Unicycler code.

For the more complex problem of _hybrid_ polishing (using both short _and_ long reads to polish an assembly), I have some new ideas that aren't yet implemented. If and when I get them working, I'll retire `unicycler_polish` for good.

Ryan
