### ISSUE TITLE
Where does the SPAdes --meta flag go???

### ISSUE THREAD

**Issue by judzen** [rrwick/Unicycler#80]
Just curious (because I see it in the log(s) all of the time) about SPAdes --meta flag for assembly of short read metagenomic data.  

I wondered where to specify this flag and/or where to edit any config files if necessary...  

I'm interested in assembling multiple sets of paired-end reads from a metagenome data set & I'd like to see what happens with only the SPAdes portion of the pipeline...  

Thanks,
J

**Comment by rrwick** [comment]
Well, the short answer is that Unicycler doesn't do metagenomes, so that option doesn't apply!

The longer answer is that I wrote Unicycler with bacterial isolates in mind and made assumptions on that basis. Metagenomes, especially complex ones, will break those assumptions and I'm not sure how Unicycler will behave. If you really want to try, you can hack that option in where Unicycler calls SPAdes. In the spads_func.py file, change this:
```
command = [spades_path, '-o', out_dir, '-k', kmer_string, '--threads', str(threads)]
```
to this:
```
command = [spades_path, '-o', out_dir, '-k', kmer_string, '--threads', str(threads), '--meta']
```
I have no idea how well this will work, so you're on your own if you try :smile:

Ryan

**Comment by bwemheu** [comment]
I initially thought that the error correction is the same for default and metagenomic mode but noticed slight differences in the corrected reads while running the same files in both modes. Hence, I think you need to add the '--meta flag' two times to run both, error correction and assembly in metagenomic mode. 

In lines 266/267:
```
    command += ['-o', read_correction_dir, '--threads', str(threads), '--only-error-correction',
                '--phred-offset', '33', '--meta']
```
And in line 365:
```
    command = [spades_path, '-o', out_dir, '-k', kmer_string, '--threads', str(threads), '--meta']
```
