### ISSUE TITLE
can i use DipSpades instead of Spades 

### ISSUE THREAD

**Issue by AteeqKhaliq** [rrwick/Unicycler#85]
Hi,

I am a regular user of Unicycler, just wanted to know if I can use dipSpades instead of Spades for assembly? if yes, how?
Your help is appreciated. 
Regards,
Dav

**Comment by rrwick** [comment]
Well, the short answer is probably no, as Unicycler is exclusively for haploid bacterial genomes and dipSPAdes is for diploid genomes. The problem is that Unicycler makes a strong distinction between single-copy and repeat contigs, and this is all based on what a haploid assembly graph should look like. Diploid assembly graphs can look quite different (split-join-split-join between the chromosome pair) so Unicycler's assumptions probably fail.

That being said, you're of course welcome to hack away at Unicycler and try to make it work, but if so, you're on your own :smile:

Ryan
