### ISSUE TITLE
Racon not running?

### ISSUE THREAD

**Issue by nataliering** [rrwick/Unicycler#96]
Hi,

I've used Unicycler successfully in the past for long-read-only as well as hybrid assembly. However, currently when I'm trying to run a long-read-only assembly, Racon doesn't run. The assembly gets to the "Polishing miniasm assembly with Racon" stage, the polishing rounds table appears and gets the "begin" row, then immediately "Best polish" comes up, without any Racon polishes actually happening.

The correct path is found during the dependency check, and I can run Racon successfully manually.

Any ideas why this might be happening please?

Thank you,
Nat

**Comment by mictadlo** [comment]
I think racon has changed recently. Maybe Unicycler need to be updated.

**Comment by kapsakcj** [comment]
Unicycler was built using Racon's first version, v0.5, and Racon was recently upgraded to a new version. I would check to make sure that you have v0.5 installed before running Unicycler again.

**Comment by mictadlo** [comment]
The easiest way to get racon v0.5 is with [bioconda](https://bioconda.github.io/) 
`conda install racon=0.5.0`

The newest Racon version accepts now FASTA files which could lead to lower memory usage. Do you have any plans to update Unicycler?

**Comment by mictadlo** [comment]
New Racon [pipeline](https://github.com/isovic/racon/issues/69#issuecomment-381781156)

**Comment by rrwick** [comment]
I've just released a new version of Unicycler (v0.4.6) which I think supports both the old and new versions of Racon. And yes, the newer versions of Racon are indeed faster - very nice!

I'll close this issue now (optimistically assuming it all works now), but please let me know if you still have any problems with Racon in Unicycler.

Ryan

**Comment by chen318liang** [comment]
> I've just released a new version of Unicycler (v0.4.7) which I think supports both the old and new versions of Racon. And yes, the newer versions of Racon are indeed faster - very nice!
> 
> I'll close this issue now (optimistically assuming it all works now), but please let me know if you still have any problems with Racon in Unicycler.
> 
> Ryan


### hi, Ryan,
Now I use unicycler (v0.4.7) to do the polish. but similar problem appears. My commands is "unicycler_polish -1 ../../../MC_1.fastq -2 ../../../MC_2.fastq --long_reads ../../../Zymo-GridION-EVEN-BB-SN.fq -a ../bins/Pseudomonas_aeruginosa.fasta --threads 30". it stops when the program running to Round 20. 

Round 20: Long read polish, small variants
2019-01-09 12:48:12   minimap -t 30 017_2_polish.fasta ../../../Zymo-GridION-EVEN-BB-SN.fq | /ELK2/wangjun/software/miniconda3/envs/bio/bin/racon -t 30 ../../../Zymo-GridION-EVEN-BB-SN.fq - 017_2_polish.fasta 0
20_1_racon_polish.fasta
2019-01-09 12:48:12   nucmer -p nucmer 017_2_polish.fasta 020_1_racon_polish.fasta
ERROR: The following critical files could not be used
/ELK2/wangjun/chenl/Zymo_Community_Standards_data/Zymo-GridION-EVEN_operms/sample_output/P.aeruginosa_nanopore/020_1_racon_polish.fasta
Check your paths and file permissions and try again

###  When I change the racon version to 0.5.0, the program run successfully. could you update this error in next version of unicycler because the new racon is faster.
